Controllers/AccessController.cs
using GestionPrueba.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Net.Mail;

namespace Gestion.Controllers
{
    public class AccessController : Controller
    {

        private readonly GestionPContext2 _contexto;

        public AccessController(GestionPContext2 contexto)
        {
            _contexto = contexto;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult StartRecovery()
        {
            Usuario model = new Usuario();
            return View(model);
        }

        [HttpPost]
        public IActionResult StartRecovery(Usuario model)
        {

            using (SqlConnection con = new(_contexto.Conexion))
            {
                using (SqlCommand cmd = new("sp_recovery", con))
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.Add("@usuario", System.Data.SqlDbType.VarChar).Value = model.Usuario1;
                    cmd.Parameters.Add("@correo", System.Data.SqlDbType.VarChar).Value = model.Correo;
                    con.Open();
                    var dr = cmd.ExecuteReader();
                    while (dr.Read())
                    {
                        if (dr["usuario"] != null && model.Usuario1 != null)
                        {
                            SendEmail(model.Correo, dr["contraseña"].ToString());
                            return RedirectToAction("Login", "Cuenta");
                        }
                        else
                        {
                            ViewBag.Error = "Credenciales incorrectas o cuenta no registrada";
                        }
                    }
                    con.Close();
                }
                return View();
            }

        }

        #region
        public void SendEmail(string email, string rContraseña)
        {
            MailMessage mailMessage = new MailMessage("ben.wingo.website@gmail.com", email, "Recuperar Contraseña",
                "<p>Contraseña</p><h3>" + rContraseña + "</h3>");
            mailMessage.IsBodyHtml = true;

            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com");
            smtpClient.EnableSsl = true;
            smtpClient.UseDefaultCredentials = false;
            smtpClient.Port = 587;
            smtpClient.Credentials = new System.Net.NetworkCredential("ben.wingo.website@gmail.com", "qrajegkqomoxzimp");

            smtpClient.Send(mailMessage);

            smtpClient.Dispose();
        }

        #endregion

    }
}

Controllers/CuentaController.cs
using GestionPrueba.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Security.Claims;

namespace GestionPrueba.Controllers
{
    public class CuentaController : Controller
    {
        private readonly GestionPContext2 _contexto;

        public CuentaController(GestionPContext2 contexto)
        {
            _contexto = contexto;
        }

        public IActionResult Login()
        {
            ClaimsPrincipal c = HttpContext.User;
            if (c.Identity != null)
            {
                if (c.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Index", "Home");
                }
                    
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Usuario u)
        {
            try
            {
                using (SqlConnection con = new(_contexto.Conexion))
                {
                    using (SqlCommand cmd = new("sp_validar", con))
                    {
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd.Parameters.Add("@usuario", System.Data.SqlDbType.VarChar).Value = u.Usuario1;
                        cmd.Parameters.Add("@contraseña", System.Data.SqlDbType.VarChar).Value = u.Contraseña;
                        con.Open();
                        var dr = cmd.ExecuteReader();

                        while (dr.Read())
                        {
                            if (dr["usuario"] != null && u.Usuario1 != null)
                            {
                                List<Claim> c = new List<Claim>()
                                {
                                    new Claim(ClaimTypes.NameIdentifier, u.Contraseña),
                                    new Claim(ClaimTypes.Name, dr["cargo"].ToString())
                                };

                                ClaimsIdentity ci = new(c, CookieAuthenticationDefaults.AuthenticationScheme);
                                AuthenticationProperties p = new();

                                p.AllowRefresh = true;
                                p.IsPersistent = u.MantenerActivo;

                                //Tiempor de expiración de sesión
                                if (!u.MantenerActivo)
                                {
                                    p.ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(3);
                                }
                                else
                                {
                                    p.ExpiresUtc = DateTimeOffset.UtcNow.AddDays(1);
                                }
                                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(ci), p);
                                if (dr["cargo"].ToString() == "Gerente")
                                    return RedirectToAction("Index", "Home");
                                else if (dr["cargo"].ToString() == "Mesero")
                                    return RedirectToAction("Index", "Pedidos");
                                else if (dr["cargo"].ToString() == "Cocinero")
                                    return RedirectToAction("IndexCocinero", "Pedidos");
                            }
                            else
                            {
                                
                                ViewBag.Error = "Credenciales incorrectas o cuenta no registrada";
                            }
                        }
                        con.Close();
                    }
                    return View();
                }
            }
            catch (System.Exception ex)
            {
                TempData["dat"] = "Usuario no eliminado";
                
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;

namespace GestionPrueba.Controllers
{
    public class InicioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Bebidas()
        {
            return View("Bebidas");
        }
        public IActionResult Snack()
        {
            return View("Snack");
        }
        public IActionResult Regresar()
        {
            return View("Index");
        }
      
    }
}

Views/Cuenta/Inicio.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Cuenta/Login.cshtml
@model Usuario

<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/menu.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/logincss.css" asp-append-version="true" />

</head>

<body class="fondoLogin">
  
    <div class="btnRegreso">
        <a asp-action="Index" asp-controller="Inicio"><img class="FRegresar" src="~/img/Login/FlechaRegreso.png" /></a>
        
    </div>
    <div class="RFondo">
        <img class="logoU" src="~/img/Logo_Establecimiento.png" />
        <form method="post" asp-action="Login" asp-controller="Cuenta">
            <div class="RFondo2">
                <div class ="titulo">
                    <p>Login</p>
                </div>
                <!--<img class="titulo" src="~/img/Login/TituloLogin.png" /> -->
                <div class="RUsuario">
                    <img class="imglogin" src="~/img/Login/Usuario.png" />
                    <input class="txt_info" type="text" placeholder="Usuario" required asp-for="Usuario1">

                </div>

                <div class="RContraseña">
                    <img class="imglogin" src="~/img/Login/Contraseña.png" />
                    <input class="txt_info" type="password" placeholder="Contraseña" required asp-for="Contraseña">

                </div>

                <div class="Rsesion">
                    <label class="txt_login">
                        <input class="txt_login" type="checkbox" asp-for="MantenerActivo">Recordar sesión
                    </label>
                </div>
                <div class="ROlvidar">
                    <label class="txt_login">
                        ¿Olvidaste tu contraseña? Haz clic en
                        <a class="txt_login" asp-area="" asp-controller="Access" asp-action="StartRecovery">recuperar</a>
                    </label>
                </div>
                <button class="BIngresa txt_login2" type="submit">Ingresar</button>
            </div>

        </form>
    </div>




</body>

@section Scripts {

    <script>
       @if (TempData.ContainsKey("dat"))
    {
        <text>
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: 'Datos incorrectos'
            });
        </text>
    }
            
    </script>
}