Models/Pedido.cs
using Microsoft.Identity.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GestionPrueba.Models;

public partial class Pedido
{
    [Key]
    public int IdPedido { get; set; }

    public int IdProducto { get; set; }

    public int Usuario { get; set; }

    [Display(Name = "Cantidad*", Prompt = "Ingresa la cantidad")]
    [Required(ErrorMessage = "Cantidad obligatoria")]
    public int Cantidad { get; set; }


    [Display(Name = "Número de mesa*", Prompt = "Ingresa el número de mesa")]
    [Required(ErrorMessage = "número de mesa obligatorio")]
    public int NumeroMesa { get; set; }


    [Display(Name = "Nota*", Prompt = "Ingresa alguna nota sobre el pedido")]

    public string Nota { get; set; } = null!;

    [Display(Name = "Estatus*")]
    [Required(ErrorMessage = "Estatus obligatorio")]
    public string Estatus { get; set; } = null!;
    [Display(Name = "IdProducto*")]
    public virtual Producto IdProductoNavigation { get; set; } = null!;
    [Display(Name = "Mesero*")]
    public virtual Usuario UsuarioNavigation { get; set; } = null!;

}

Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionPrueba.Models;
using System.Security.Claims;
using System.Data.SqlClient;
using System.Data;

namespace GestionPrueba.Controllers
{
    public class PedidosController : Controller
    {
        private readonly GestionPContext _context;
        private readonly GestionPContext2 _contexto;

        public PedidosController(GestionPContext context, GestionPContext2 contexto)
        {
            _context = context;
            _contexto = contexto;
        }

     

        public async Task<IActionResult> Index3()
        {
            return _context.Productos != null ?
                        View(await _context.Productos.ToListAsync()) :
                        Problem("Entity set 'GestionPContext.Productos'  is null.");
        }
        public async Task<IActionResult> IndexCocinero()
        {
            return _context.Productos != null ?
                        View(await _context.Productos.ToListAsync()) :
                        Problem("Entity set 'GestionPContext.Productos'  is null.");
        }

        public async Task<IActionResult> IndexTodos()
        {
            var gestionPContext = _context.Pedidos.Include(p => p.IdProductoNavigation).Include(p => p.UsuarioNavigation);
            return View(await gestionPContext.ToListAsync());
        }
        public async Task<IActionResult> Index2()
        {
            ClaimsPrincipal c = HttpContext.User;
            if (c.Identity != null)
            {
                if (c.Identity.IsAuthenticated)
                    if (c.FindFirst(ClaimTypes.Name)?.Value == "Cocinero")
                    {
                        List<Pedido> lista = new List<Pedido>();

                        using (SqlConnection con = new(_contexto.Conexion))
                        {
                            using (SqlCommand cmd = new("sp_pedidos1", con))
                            {
                                try
                                {
                                    cmd.CommandType = CommandType.StoredProcedure;
                                    con.Open();
                                    var dr = cmd.ExecuteReader();
                                    while (dr.Read())
                                    {
                                        lista.Add(new Pedido()
                                        {
                                            IdPedido = (int)dr["idPedido"],
                                            IdProducto = (int)dr["idProducto"],
                                            Usuario = (int)dr["usuario"],
                                            Cantidad = (int)dr["Cantidad"],
                                            NumeroMesa = (int)dr["numeroMesa"],
                                            Nota = dr["Nota"].ToString(),
                                            Estatus = dr["estatus"].ToString()
                                        });
                                    }
                                }
                                catch (Exception)
                                {
                                    
                                    throw;
                                }
                                
                                con.Close();
                            }
                        }
                        return View(lista);
                    }

            }
            return RedirectToAction("Login", "Cuenta");
        }


        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
            //var gestionPContext = _context.Pedidos.Include(p => p.IdProductoNavigation).Include(p => p.UsuarioNavigation);
            //return View(await gestionPContext.ToListAsync());
            ClaimsPrincipal c = HttpContext.User;
            if (c.Identity != null)
            {
                if (c.Identity.IsAuthenticated)
                    if (c.FindFirst(ClaimTypes.Name)?.Value == "Mesero")
                    {
                        List<Pedido> lista = new List<Pedido>();

                        using (SqlConnection con = new(_contexto.Conexion))
                        {
                            using (SqlCommand cmd = new("sp_pedidos1", con))
                            {
                                try
                                {
                                    cmd.CommandType = CommandType.StoredProcedure;
                                    con.Open();
                                    var dr = cmd.ExecuteReader();
                                    while (dr.Read())
                                    {
                                        lista.Add(new Pedido()
                                        {
                                            IdPedido = (int)dr["idPedido"],
                                            IdProducto = (int)dr["idProducto"],
                                            Usuario = (int)dr["usuario"],
                                            Cantidad = (int)dr["Cantidad"],
                                            NumeroMesa = (int)dr["numeroMesa"],
                                            Nota = dr["Nota"].ToString(),
                                            Estatus = dr["estatus"].ToString()
                                        });
                                    }
                                }
                                catch (Exception)
                                {

                                    throw;
                                }

                                con.Close();
                            }
                        }
                        return View(lista);
                    }

            }
            return RedirectToAction("Login", "Cuenta");

        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .Include(p => p.IdProductoNavigation)
                .Include(p => p.UsuarioNavigation)
                .FirstOrDefaultAsync(m => m.IdPedido == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "Nombre");
            ViewData["Usuario"] = new SelectList(_context.Usuarios, "Usuario1", "Usuario1");
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPedido,IdProducto,Usuario,Cantidad,NumeroMesa,Nota,Estatus")] Pedido pedido)
        {
            if (!ModelState.IsValid)
            {
                try
                {
                                _context.Add(pedido);
                                await _context.SaveChangesAsync();
                                return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    TempData["error"] = "Pedido no guardado";

                } 
            }
            
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "Nombre", pedido.IdProducto);
            ViewData["Usuario"] = new SelectList(_context.Usuarios, "Usuario1", "Usuario1", pedido.Usuario);
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "Nombre", pedido.IdProducto);
            ViewData["Usuario"] = new SelectList(_context.Usuarios, "Usuario1", "Usuario1", pedido.Usuario);
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPedido,IdProducto,Usuario,Cantidad,NumeroMesa,Nota,Estatus")] Pedido pedido)
        {
            if (id != pedido.IdPedido)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.IdPedido))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdProducto"] = new SelectList(_context.Productos, "IdProducto", "Nombre", pedido.IdProducto);

Views/Pedidos/Create.cshtml
@model GestionPrueba.Models.Pedido

@{
    ViewData["Title"] = "Create";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Formulario.css" asp-append-version="true" />
</head>

<body class="FondoC">
    <header>

        <nav>
            <img class="logoE" src="~/img/Logo_Establecimiento.png" />
            <ul class="menu-horizontal">
                <li>
                    <a asp-action="Index" asp-controller="Pedidos" class="EmMenu">Pedidos</a>
                </li>
                <li>
                    <a asp-action="Index3" class="ProMenu">Productos</a>
                </li>
                <li class="IS"><a asp-action="Salir" asp-controller="Home">Salir</a></li>
            </ul>
        </nav>
    </header>

    <div class="FFondo">
        <div class="Ftitulo">
            <p class="">Agregar Pedido</p>
        </div>
        <div class="FFondo2">
            <form asp-action="Create" id="formulario" onsubmit="enviar(event)">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div> 
                 
                <div class="FIdProducto">
                    <label asp-for="IdProducto" class="Ftxt"></label><br />
                    <select asp-for="IdProducto" class="FInfo Ftxt" asp-items="ViewBag.IdProducto"></select>
                </div>
                <div class="FUsuarioPe">
                    <label asp-for="Usuario" class="Ftxt"></label><br />
                    <select asp-for="Usuario" class="FInfo Ftxt" asp-items="ViewBag.Usuario"></select>
                </div>
                <div class="FCantidad">
                    <label asp-for="Cantidad" class="Ftxt"></label><br />
                    <select asp-for="Cantidad" class="FInfo Ftxt">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                    <span asp-validation-for="Cantidad" class="FtxtE"></span>
                </div>                
                <div class="FMesa">
                    <label asp-for="NumeroMesa" class="Ftxt"></label><br />
                    <input asp-for="NumeroMesa" class="FInfo Ftxt" />
                    <span asp-validation-for="NumeroMesa" class="FtxtE2"></span>
                </div>
                <div class="FNota">
                    <label asp-for="Nota" class="Ftxt"></label><br />
                    <input asp-for="Nota" class="FtxtI Ftxt" />
                    <span asp-validation-for="Nota" class="FtxtE3"></span>
                </div>
                <div class="FEstatus">
                    <input type="hidden" asp-for="Estatus" value="En espera" />
                </div>
                <div class="Fbtn">
                    <input type="submit" value="Guardar" class="FbtnG FBtxt" />
                    <div class="FbtnR ">
                        <a asp-action="Index">Regresar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function enviar(e) {
            e.preventDefault();

            Swal.fire({
              title: 'Pedido registrado exitosamente',
              icon: 'success',
              //showCancelButton:true;
              confirmButtonText:'Ok',
              timer: 3000
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    
                    const formulario = document.getElementById('formulario');
                    formulario.submit();
                }
            });
        }

        @if (TempData.ContainsKey("Error"))
    {
        <text>
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: '@TempData["Error"]'
            });
        </text>
    }

    </script>
}

Views/Pedidos/Delete.cshtml
@model GestionPrueba.Models.Pedido

@{
    ViewData["Title"] = "Delete";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Formulario.css" asp-append-version="true" />
</head>



<body>
    <header>

        <nav>
            <img class="logoE" src="~/img/Logo_Establecimiento.png" />
            <ul class="menu-horizontal">
                <li>
                    <a asp-action="Index" asp-controller="Pedidos" class="EmMenu">Pedidos</a>
                </li>
                <li>
                    <a asp-action="Index3" class="ProMenu">Productos</a>
                </li>
                <li class="IS"><a asp-action="Salir" asp-controller="Home">Salir</a></li>
            </ul>
        </nav>
    </header>
    <div class="FFondo">
        <div class="FtituloD">
            <p class="">Deliminar Usuario</p>
        </div>
        <h3 class="pregunta">¿Está seguro de que quiere eliminar el usuario?</h3>
        <dl class="FFondo2">
            <dt class="DCantidad Ftxt">
                @Html.DisplayNameFor(model => model.Cantidad)
            </dt>
            <dd class="ICantidad Ftxt">
                @Html.DisplayFor(model => model.Cantidad)
            </dd>
            <dt class="DMesa Ftxt">
                @Html.DisplayNameFor(model => model.NumeroMesa)
            </dt>
            <dd class="IMesa Ftxt">
                @Html.DisplayFor(model => model.NumeroMesa)
            </dd>
            <dt class="DNota Ftxt">
                @Html.DisplayNameFor(model => model.Nota)
            </dt>
            <dd class="INota Ftxt">
                @Html.DisplayFor(model => model.Nota)
            </dd>
            <dt class="DEstatus Ftxt">
                @Html.DisplayNameFor(model => model.Estatus)
            </dt>
            <dd class="IEstatus Ftxt">
                @Html.DisplayFor(model => model.Estatus)
            </dd>
            <dt class="DAditivos Ftxt">
                @Html.DisplayNameFor(model => model.IdProductoNavigation)
            </dt>
            <dd class="IAditivos Ftxt">
                @Html.DisplayFor(model => model.IdProductoNavigation.Aditivos)
            </dd>
            <dt class="DUsuarioPe Ftxt">
                @Html.DisplayNameFor(model => model.UsuarioNavigation)
            </dt>
            <dd class="IUsuarioPe Ftxt">
                @Html.DisplayFor(model => model.UsuarioNavigation.ApellidoP)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="IdPedido" />
            <input type="hidden" asp-for="IdProducto" />
            <input type="hidden" asp-for="Usuario" />
            <input type="hidden" asp-for="Cantidad" />
            <input type="hidden" asp-for="NumeroMesa" />
            <input type="hidden" asp-for="Nota" />
            <input type="hidden" asp-for="Estatus" value="Cancelado" />
            <div class="Dbtn">
                <input type="submit" value="Delete" class="FbtnB Ftxt" /> |
                <div class="DbtnR Ftxt">
                    <a asp-action="Index">Regresar</a>
                </div>
            </div>

        </form>
    </div>
</body>

Views/Pedidos/Details.cshtml
@model GestionPrueba.Models.Pedido

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroMesa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroMesa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProductoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProductoNavigation.Aditivos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsuarioNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UsuarioNavigation.ApellidoP)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdPedido">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Pedidos/Edit.cshtml
@model GestionPrueba.Models.Pedido

@{
    ViewData["Title"] = "Edit";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Formulario.css" asp-append-version="true" />
</head>

<body>
    <header>

        <nav>
            <img class="logoE" src="~/img/Logo_Establecimiento.png" />
            <ul class="menu-horizontal">
                <li>
                    <a asp-action="Index" asp-controller="Pedidos" class="EmMenu">Pedidos</a>
                </li>
                <li>
                    <a asp-action="Index3" class="ProMenu">Productos</a>
                </li>
                <li class="IS"><a asp-action="Salir" asp-controller="Home">Salir</a></li>
            </ul>
        </nav>
    </header>

    <div class="FFondo">
        <div class="Ftitulo">
            <p class="">Modificar Pedido</p>
        </div>
        <div class="FFondo2">
            <form asp-action="Edit" id="formulario" onsubmit="enviar(event)">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="FIdPedido">
                    <label asp-for="IdPedido" class="Ftxt"></label><br />
                    <input asp-for="IdPedido" class="FInfo Ftxt" readonly="readonly" />
                </div>
                <div class="FIdProducto">
                    <label asp-for="IdProducto" class="Ftxt"></label><br />
                    <select asp-for="IdProducto" class="FInfo Ftxt" asp-items="ViewBag.IdProducto"></select>
                    <span asp-validation-for="IdProducto" class="text-danger"></span>
                </div>
                <div class="FUsuarioPe">
                    <label asp-for="Usuario" class="Ftxt"></label><br />
                    <select asp-for="Usuario" class="FInfo Ftxt" asp-items="ViewBag.Usuario"></select>
                    <span asp-validation-for="Usuario" class="text-danger"></span>
                </div>
                <div class="FCantidad">
                    <label asp-for="Cantidad" class="Ftxt"></label><br />
                    <select asp-for="Cantidad" class="FInfo Ftxt">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                    </select>
                    <span asp-validation-for="Cantidad" class="FtxtE"></span>
                </div>
                <div class="FMesa">
                    <label asp-for="NumeroMesa" class="Ftxt"></label><br />
                    <input asp-for="NumeroMesa" class="FInfo Ftxt" />
                    <span asp-validation-for="NumeroMesa" class="FtxtE2"></span>
                </div>
                <div class="FNota">
                    <label asp-for="Nota" class="Ftxt"></label><br />
                    <input asp-for="Nota" class="FInfo Ftxt" />
                    <span asp-validation-for="Nota" class="FtxtE3"></span>
                </div>
                <div class="FEstatusPe">
                    <label asp-for="Estatus" class="Ftxt"></label><br />
                    <!--</a><input asp-for="Estatus" class="FInfo Ftxt" />-->
                    <select asp-for="Estatus" class="FInfo Ftxt">
                        <option value="Cancelado">Cancelado</option>
                        <option value="En espera">En espera</option>
                        <option value="Realizado">Realizado</option>
                        </select>
                    <span asp-validation-for="Estatus" class="FtxtE3"></span>
                </div>
                <div class="Fbtn">
                    <input type="submit" value="Guardar" class="FbtnG FBtxt" />
                    <div class="FbtnR ">
                        <a asp-action="Index">Regresar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function enviar(e) {
            e.preventDefault();

            Swal.fire({
              title: 'Modificación exitosa',
              icon: 'success',
              //showCancelButton:true;
              confirmButtonText:'Ok',
              timer: 3000
            }).then((result) => {
                /* Read more about isConfirmed, isDenied below */
                if (result.isConfirmed) {
                    
                    const formulario = document.getElementById('formulario');
                    formulario.submit();
                }
            });
        }

        
    

    </script>
}

Views/Pedidos/Index.cshtml
@model IEnumerable<GestionPrueba.Models.Pedido>

@{
    ViewData["Title"] = "Index";
}

<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Tablas.css" asp-append-version="true" />
</head>

<body>
    <header>

        <nav>
            <img class="logoE" src="~/img/Logo_Establecimiento.png" />
            <ul class="menu-horizontal">
                <li>
                    <a asp-action="Index" asp-controller="Pedidos" class="EmMenu">Pedidos</a>
                </li>
                <li>
                    <a asp-action="Index3" class="ProMenu">Productos</a>
                </li>
                <li class="IS"><a asp-action="Salir" asp-controller="Home">Salir</a></li>
            </ul>
        </nav>
    </header>

    <div class="tituloT">
        <p>Pedidos</p>
    </div>
    <!-- <img class="tituloT" src="~/img/Pedidos.png" />-->

   
    <div class="TodosU">
        <a asp-action="IndexTodos"><img src="~/img/Iconos/ActualizarPe.png" />Todos los pedidos</a>
    </div>

    <div class="BtnAgragar">
        <a asp-action="Create"><img src="~/img/Iconos/MasAgregar.png" />Agregar Pedido</a>
    </div>
     
   
    <table class="Tabla2">
        <thead>
            <tr class="Tabla1 ">
                <th class="ValorT">
                    IdPedido
                </th>
                <th class="ValorT">
                    Cantidad
                </th>
                <th class="ValorT">
                    NumeroMesa
                </th>
                <th class="ValorT">
                    Nota
                </th>
                <th class="ValorT">
                    Estatus
                </th>
                <th class="ValorT">
                    IdProducto
                </th>
                <th class="ValorT">
                    Usuario
                </th>
                <th class="ValorT">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="ValorT2">
                    <td>
                        @Html.DisplayFor(modelItem => item.IdPedido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cantidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroMesa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Usuario)
                    </td>
                    <td>
                        <div class="btns">
                            <div class="btnEditar2">
                                <a asp-action="Edit" asp-route-id="@item.IdPedido"><img src="~/img/Iconos/Modificar.png" /></a>
                            </div>
                            <div class="btnEliminar2">

                                <form asp-action="Delete" asp-route-id="@item.IdPedido"  id="formulario" onsubmit="enviar(event)">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <input type="hidden" name="IdPedido" id="IdPedido" asp-for="@item.IdPedido" />
                                    <input type="hidden" name="IdProducto" id="IdProducto" asp-for="@item.IdProducto" />
                                    <input type="hidden" name="Usuario" id="Usuario" asp-for="@item.Usuario" />
                                    <input type="hidden" name="Cantidad" id="Cantidad" asp-for="@item.Cantidad" />
                                    <input type="hidden" name="NumeroMesa" id="NumeroMesa" asp-for="@item.NumeroMesa" />
                                    <input type="hidden" name="Nota" id="Nota" asp-for="@item.Nota" />
                                    <input type="hidden" name="Estatus" id="Estatus" asp-for="@item.Estatus" value="Cancelado" />
                                    <button type="submit" style="cursor: pointer" class="btn btn-danger"><img src="~/img/Iconos/Eliminar.png" onclick="confirmar()"/></button>
                                </form>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</body>

@section Scripts{
<script>
        

    function confirmar(){
             Swal.fire('Excelente', "Pedido eliminado correctamente", 'success', 15000);
        }

</script>

}