Controllers/CuentaController.cs
using GestionPrueba.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Security.Claims;

namespace GestionPrueba.Controllers
{
    public class CuentaController : Controller
    {
        private readonly GestionPContext2 _contexto;

        public CuentaController(GestionPContext2 contexto)
        {
            _contexto = contexto;
        }

        public IActionResult Login()
        {
            ClaimsPrincipal c = HttpContext.User;
            if (c.Identity != null)
            {
                if (c.Identity.IsAuthenticated)
                {
                    return RedirectToAction("Index", "Home");
                }
                    
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Usuario u)
        {
            try
            {
                using (SqlConnection con = new(_contexto.Conexion))
                {
                    using (SqlCommand cmd = new("sp_validar", con))
                    {
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd.Parameters.Add("@usuario", System.Data.SqlDbType.VarChar).Value = u.Usuario1;
                        cmd.Parameters.Add("@contraseña", System.Data.SqlDbType.VarChar).Value = u.Contraseña;
                        con.Open();
                        var dr = cmd.ExecuteReader();

                        while (dr.Read())
                        {
                            if (dr["usuario"] != null && u.Usuario1 != null)
                            {
                                List<Claim> c = new List<Claim>()
                                {
                                    new Claim(ClaimTypes.NameIdentifier, u.Contraseña),
                                    new Claim(ClaimTypes.Name, dr["cargo"].ToString())
                                };

                                ClaimsIdentity ci = new(c, CookieAuthenticationDefaults.AuthenticationScheme);
                                AuthenticationProperties p = new();

                                p.AllowRefresh = true;
                                p.IsPersistent = u.MantenerActivo;

                                //Tiempor de expiración de sesión
                                if (!u.MantenerActivo)
                                {
                                    p.ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(3);
                                }
                                else
                                {
                                    p.ExpiresUtc = DateTimeOffset.UtcNow.AddDays(1);
                                }
                                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(ci), p);
                                if (dr["cargo"].ToString() == "Gerente")
                                    return RedirectToAction("Index", "Home");
                                else if (dr["cargo"].ToString() == "Mesero")
                                    return RedirectToAction("Index", "Pedidos");
                                else if (dr["cargo"].ToString() == "Cocinero")
                                    return RedirectToAction("IndexCocinero", "Pedidos");
                            }
                            else
                            {
                                
                                ViewBag.Error = "Credenciales incorrectas o cuenta no registrada";
                            }
                        }
                        con.Close();
                    }
                    return View();
                }
            }
            catch (System.Exception ex)
            {
                TempData["dat"] = "Usuario no eliminado";
                
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;

namespace GestionPrueba.Controllers
{
    public class InicioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Bebidas()
        {
            return View("Bebidas");
        }
        public IActionResult Snack()
        {
            return View("Snack");
        }
        public IActionResult Regresar()
        {
            return View("Index");
        }
      
    }
}

Views/Inicio/Bebidas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/menu.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Bebidas.css" asp-append-version="true" />
</head>

<body class="PagBebidas">
    <header>

        <nav class="">
            <a asp-action="Index" asp-controller="Home"><img class="logoE" src="~/img/Logo_Establecimiento.png" /></a>
            <ul class="menu-horizontal">
                <li>
                    <a>Productos</a>
                    <ul class="menu-vertical">
                        <li><a asp-action="Bebidas" asp-controller="Inicio">Bebidas</a></li>
                        <li><a asp-action="Snack" asp-controller="Inicio">Snack's</a></li>
                    </ul>
                </li>
                <li>
                    <a class="ConMenu">Contáctanos</a>
                    <ul class="menu-vertical ConM">
                        <li><a href="https://www.facebook.com/">Facebook</a></li>
                    </ul>
                </li>

                <li class="IS"><a asp-action="Login" asp-controller="Cuenta">Iniciar Sesión</a></li>
            </ul>
        </nav>
    </header>

    <div>
        
        <div class="titulo">
            <hr class="linea1" />
            <p>Bebidas</p>
            <hr class="linea2" />
        </div>
        
       
        
        <div class="Contenido2">
            <div class="Contenido3">
                <div class="titulo1">
                    <p>Mojitos</p>
                    <hr />
                </div>
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Bebidas/Bebida1.png" />
                        <h2>Mojito azul(Pitufo)</h2>
                        Escarchado con pulpa de tamarindo color<br />
                        azul y miguelito sabor mora azul, <br />
                        vodka nacional, kosako, agua mineral,<br />
                        lima, y limón azul.
                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto1" src="~/img/Bebidas/Bebida2.png" />
                        <h2>Mojito ultra violeta</h2>
                        vodka nacional, lima, kosako azul<br />
                        jugó de arandano o uva.
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto1" src="~/img/Bebidas/Bebida3.png" />
                        <h2>Mojito  clásico o tradicional</h2>
                        con limón, hierbabuena y menta<br />
                        Ron nacional, jarabe, agua mineral  y lima
                    </p>
                </div>

            </div>
            <div class="Contenido4">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Bebidas/Bebida4.png" />
                        <h2>Mojito de frutos rojos</h2>
                        Mora, zarzamora, fresa y jugo de arándano<br />
                        Ron nacional,jarabe, agua mineral y lima.
                    </p>
                </div>

            </div>
          
            <div class="titulo2">
                <p>Cerveza</p>
                <hr />
            </div>

            <div class="Contenido5">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto2" src="~/img/Bebidas/Cerveza.png" />
                        <h2>CERVEZA 355ml</h2>
                        Cerveza corona o victoria $30.00<br />

                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto2" src="~/img/Bebidas/MicheladaT1.png" />
                        <h2>MICHELADA<br />TRADICIONAL 500ml</h2>
                        Escarchada con sal y limon $35.00<br />
                        Con camarones $55.00
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto2" src="~/img/Bebidas/MicheladaT2.png" />
                        <h2>MICHELADA<br />TRADICIONAL 1 LITRO</h2>
                        Escarchado con sal y limon $70.00<br />
                        Con camarones $85.00
                    </p>
                </div>
            </div>
            <div class="Contenido6">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto2" src="~/img/Bebidas/Clamato1.png" />
                        <h2>CLAMA PEPE 500ml</h2><br />
                        Escarchado con chamoy, clamato y limon $50.00<br />
                        Con camarones $70.00
                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto2" src="~/img/Bebidas/Clamato2.png" />
                        <h2>CLAMA PEPE 1 LITRO</h2>
                        Escarchado con chamoy, clamato y limon $90.00<br />
                        Con camarones $100.00
                    </p>
                </div>

            </div>

            <div class="Contenido7">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto2" src="~/img/Bebidas/MCubana1.png" />
                        <h2>CUBANA 500ml</h2>
                        Escarchado con chamoy, clamato, 0<br />
                        limon y salsas $50.00<br />
                        Con camarones $70.00
                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto2" src="~/img/Bebidas/MCubana2.png" />
                        <h2>CUBANA 1 LITRO</h2>
                        Escarchado con chamoy, clamato, 0<br />
                        limon y salsas $90.00<br />
                        Con camarones $100.00
                    </p>
                </div>

            </div>

            <div class="titulo3">
                <p>Bebidas sin alcohol</p>
                <hr />
            </div>

            <div class="Contenido8">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Bebidas/Refrescos.png" />
                        <h2>REFRESCOS</h2>
                        Coca-cola, Manzanita, $25.00<br />

                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto3" src="~/img/Bebidas/Limonada.png" />
                        <h2>LIMONADA</h2>
                        Natural o mineral $45.00<br />
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto3" src="~/img/Bebidas/Naranjada.png" />
                        <h2>NARANJADA</h2>
                        Natural o mineral $45.00<br />
                    </p>
                </div>
            </div>

            <div class="Contenido9">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Bebidas/ClamatoP.png" />
                        <h2>CLAMATO PREPARADO</h2>
                        Clamato preparado $45.00<br />

                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto3" src="~/img/Bebidas/Piñada.png" />
                        <h2>PIÑADA</h2>
                        Piñada $55.00<br />
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto1" src="~/img/Bebidas/Agua1.png" />
                        <h2>AGUA NATURAL</h2>
                        Agua natural 1 litro $10.00<br />
                        Agua natural 1/2 litro $20.00

                    </p>
                </div>
            </div>




        </div>
    </div>


</body>

Views/Inicio/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />  
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    <header>

        <nav class="">
            <img class="logoE" src="~/img/Logo_Establecimiento.png" />
            <ul class="menu-horizontal">
                <li>
                    <a>Productos</a>
                    <ul class="menu-vertical">
                        <li><a asp-action="Bebidas" asp-controller="Inicio">Bebidas</a></li>
                        <li><a asp-action="Snack" asp-controller="Inicio">Snack's</a></li>
                    </ul>
                </li>
                <li>
                    <a class="ConMenu">Contáctanos</a>
                    <ul class="menu-vertical ConM">
                        <li><a href="https://www.facebook.com/">Facebook</a></li>
                    </ul>
                    
                </li>

                <li class="IS"><a asp-action="Login" asp-controller="Cuenta">Iniciar Sesión</a></li>
            </ul>
        </nav>
    </header>
  

    <div class="">
        <img class="PFoto1" src="~/img/Principal/Ben&wingo1.png" />
        <img class="PFoto2" src="~/img/Principal/Principal_hamburgusa.png" />
        <img class="PFoto3" src="~/img/Principal/Principal_frase.png" />
    </div>
</body>
<footer class="fin">
    <div class="fin2">
        ©Ben&Wingo Company
        ben&wingo.com- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

Views/Inicio/Snack.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/menu.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Snack.css" asp-append-version="true" />
</head>

<body>
    <header>

        <nav class="">
           <a asp-action="Index" asp-controller="Home"><img class="logoE" src="~/img/Logo_Establecimiento.png" /></a>
            <ul class="menu-horizontal">
                <li>
                    <a>Productos</a>
                    <ul class="menu-vertical">
                        <li><a asp-action="Bebidas" asp-controller="Inicio">Bebidas</a></li>
                        <li><a asp-action="Snack" asp-controller="Inicio">Snack's</a></li>
                    </ul>
                </li>
                <li>
                   <a class="ConMenu">Contáctanos</a>
                    <ul class="menu-vertical ConM">
                        <li><a href="https://www.facebook.com/">Facebook</a></li>
                    </ul>
                </li>

                <li class="IS"><a asp-action="Login" asp-controller="Cuenta">Iniciar Sesión</a></li>
            </ul>
        </nav>
    </header>

    <div>

        <div class="titulo">
            <hr class="linea1" />
            <p>Snack's</p>
            <hr class="linea2" />
        </div>



        <div class="Contenido2">
            <div class="Contenido3">
               
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Hamburguesa.png" />
                        <h2>HAMBURGUESAS</h2>
                        Sencilla....$60<br />
                        Sencilla con papas....$75 <br />
                        Hawaiana....$75<br />
                        Hawaiana con papas....$85<br />
                        Con tocino....$80<br />
                        Tocino con papas....$90
                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/HotDog.png" />
                        <h2>HOG DOG</h2>
                        Sencillo....$25<br />
                        Sencilla con papas....$40 <br />
                        Con tocino....$35<br />
                        Tocino con papas....$50
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Alitas.png" />
                        <h2>ALITAS</h2>
                        6 piezas....$85 <br />
                        A la BBQ<br />
                        Picositas<br />
                        Parmesano<br />
                        Mango habanero<br />
                        Tamarindo chipotle
                    </p>
                </div>
            </div>
            <div class="Contenido4">             
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Costillas.png" />
                        <h2>COSTILLAS</h2>
                        4 piezas....$100<br />
                        A las BBQ <br />
                        Adobadas<br />
                        Acompañadas con papas a la francesa
                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Nachos2.jpeg" />
                        <h2>NACHOS</h2>
                        Tradicionales....$45<br />
                        Con carne, receta especial....$80 <br />
                        Con arrachera y guacamole....$120<br />
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Nugget.jpeg" />
                        <h2>NUGGET´S DE POLLO</h2>
                        6 piezas....$35<br />
                        8 piezas....$65<br />
                        Incluye papas <br />
                        o<br />
                        cruditos
                    </p>
                </div>
            </div>

            <div class="Contenido5">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Aros.png" />
                        <h2>AROS DE CEBOLLA<br />CON PAPAS</h2>
                        6 piezas....$80<br />                        
                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Dedos.png" />
                        <h2>DEDOS DE QUESO <br /> CON PAPAS</h2>
                        6 piezas....$80<br />
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Guacamole.jpeg" />
                        <h2>GUACAMOLE CON <br /> CHICHARRÓN</h2>
                        Jitomate, cebolla, pepino<br />
                        salsa magui y limon....$100<br />
                    </p>
                </div>
            </div>

            <div class="Contenido6">
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Papas.png" />
                        <h2>PAPAS FRITAS</h2>
                        A la francesa....$55<br />
                        Papas gajo....$55<br />
                        Salchi papas....$70<br />
                    </p>
                </div>                
            </div>

            <div class="Contenido7">
                <div class="titulo1">
                    <p>Botanas</p>
                    <hr />
                </div>
                <div class="Descripcion">                  
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Palomitas.png" />
                        <br /><br />
                        <h2>PALOMITAS</h2>
                        Natural / Mantequilla....$25<br />
                    </p>
                </div>
                <div class="Descripcion2">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Chicharrones.png" />
                        <br /><br />
                        <h2>CHICHARRONES</h2>
                        Chicarrones....$25<br />
                    </p>
                </div>
                <div class="Descripcion3">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Cacahuates.png" />
                        <br /><br />
                        <h2>CACAHUATES MIXTOS</h2>
                        Cacahuates mixtos....$25<br />
                    </p>
                </div>
            </div>

            <div class="Contenido8">
                <div class="titulo2">
                    <p>Postres</p>
                    <hr />
                </div>
                <div class="Descripcion">
                    <p>
                        <img class="PFoto1" src="~/img/Snack/Duraznos.png" />
                        <br /><br />
                        <h2>DURAZNOS CON CREMA</h2>
                        Duraznos con crema....$30<br />
                    </p>
                </div>            
            </div>
           
           

            




        </div>
    </div>



</body>